steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 'deploy', 'retrieve_quiberon_video',
    '--runtime', 'python310',
    '--trigger-http',
    '--allow-unauthenticated',
    '--source', 'src/data_integration/.',
    '--region', 'europe-west1',  # Changez la région ici
    '--memory', '512Mi'  # Ajustez la mémoire ici
  ]