main:
   params: [event]
   steps:
       - init:
           assign:
               - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
               - job_name: transformation
               - job_location: europe-west1
       - callFunction:
           call: http.get
           args:
               url: ${"https://europe-west1-" + project_id + ".cloudfunctions.net/retrieve_quiberon_video"}
               timeout: 540
           result: function_response
       - run_job:
           call: googleapis.run.v1.namespaces.jobs.run
           args:
               name: ${"namespaces/" + project_id + "/jobs/" + job_name}
               location: ${job_location}
           result: job_execution
       - finish:
           return:
               code: 200
               message: "Job started successfully"