# Use the official Python image as a base
FROM python:3.9-slim


# Install system dependencies for OpenCV and others
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    wget  # Install wget or curl if your script needs them to download files

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt to the working directory
COPY requirements.txt .

# Install any necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY . .


# dowload the model configuration file 


RUN chmod +x dowload_file_for_yolo.sh

# Command to run both Python programs when the container starts
# You can also run one program at a time by changing the command
CMD ["python", "transform.py"]  # Replace with "app2.py" for the second program